### PR TITLE
Testing out the `!test` command

### PR DESCRIPTION
**Pull request by CodeGat**

### CODE REVIEW

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
Has an issue with unrelated histories
\

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro

**Comment by aidanheerdegen** [comment]
!test repro

**Comment by aidanheerdegen** [comment]
!test repro commit

**Comment by CodeGat** [comment]
!test repro

**Comment by CodeGat** [comment]
!test repro commit

**Comment by CodeGat** [comment]
!test repro commit

**Comment by CodeGat** [comment]
!test repro commit

**Comment by CodeGat** [comment]
!test repro commit

**Comment by CodeGat** [comment]
!test something

**Comment by CodeGat** [comment]
!test repro thingo

**Comment by aidanheerdegen** [comment]
> This result has been committed to this PR, if it differs from the current HEAD

Can we be more definitive and check if a `commit` will/has happen/ed and alter the message accordingly?

Why does `!test repro thingo` work? Is it ignoring the extra `thingo` argument?

**Comment by CodeGat** [comment]
Yes it is ignoring the commands that it doesn't understand - should it fail?

**Comment by CodeGat** [comment]
And for

> Can we be more definitive and check if a commit will/has happen/ed and alter the message accordingly?

I think we have the info to do that, will update

**Comment by aidanheerdegen** [comment]
> Yes it is ignoring the commands that it doesn't understand - should it fail?

I kinda think it should if only because we're planning to be able to add useful options, and I'd hate for people to *think* they've put in the correct command but it is silently ignored.

**Comment by aidanheerdegen** [comment]
> I think we have the info to do that, will update

Awesome! Thanks man.

**Comment by CodeGat** [comment]
!test repro adshdsaihasdihs

**Comment by CodeGat** [comment]
!test repro commit osidfj sdfkjoi

**Comment by CodeGat** [comment]
!test repro commit something

**Pull request closed without merging**
